/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "vreventinfostoreservice_constants.h"

namespace CRDHN { namespace VR {

const vreventinfostoreserviceConstants g_vreventinfostoreservice_constants;

vreventinfostoreserviceConstants::vreventinfostoreserviceConstants() {
}

}} // namespace

