/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef vrregistrationcodesstoreservice_CONSTANTS_H
#define vrregistrationcodesstoreservice_CONSTANTS_H

#include "vrregistrationcodesstoreservice_types.h"

namespace CRDHN { namespace VR {

class vrregistrationcodesstoreserviceConstants {
 public:
  vrregistrationcodesstoreserviceConstants();

};

extern const vrregistrationcodesstoreserviceConstants g_vrregistrationcodesstoreservice_constants;

}} // namespace

#endif
