/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef TVRDailyInjectionsStoreService_H
#define TVRDailyInjectionsStoreService_H

#include <thrift/TDispatchProcessor.h>
#include "vrdailyinjectionsstoreservice_types.h"

namespace CRDHN { namespace VR {

class TVRDailyInjectionsStoreServiceIf {
 public:
  virtual ~TVRDailyInjectionsStoreServiceIf() {}
  virtual bool add(const std::string& key, const  ::CRDHN::VR::Data::TRID registrationId) = 0;
  virtual void get( ::CRDHN::VR::Data::TDailyInjections& _return, const std::string& key) = 0;
  virtual bool remove(const std::string& key) = 0;
};

class TVRDailyInjectionsStoreServiceIfFactory {
 public:
  typedef TVRDailyInjectionsStoreServiceIf Handler;

  virtual ~TVRDailyInjectionsStoreServiceIfFactory() {}

  virtual TVRDailyInjectionsStoreServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(TVRDailyInjectionsStoreServiceIf* /* handler */) = 0;
};

class TVRDailyInjectionsStoreServiceIfSingletonFactory : virtual public TVRDailyInjectionsStoreServiceIfFactory {
 public:
  TVRDailyInjectionsStoreServiceIfSingletonFactory(const boost::shared_ptr<TVRDailyInjectionsStoreServiceIf>& iface) : iface_(iface) {}
  virtual ~TVRDailyInjectionsStoreServiceIfSingletonFactory() {}

  virtual TVRDailyInjectionsStoreServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(TVRDailyInjectionsStoreServiceIf* /* handler */) {}

 protected:
  boost::shared_ptr<TVRDailyInjectionsStoreServiceIf> iface_;
};

class TVRDailyInjectionsStoreServiceNull : virtual public TVRDailyInjectionsStoreServiceIf {
 public:
  virtual ~TVRDailyInjectionsStoreServiceNull() {}
  bool add(const std::string& /* key */, const  ::CRDHN::VR::Data::TRID /* registrationId */) {
    bool _return = false;
    return _return;
  }
  void get( ::CRDHN::VR::Data::TDailyInjections& /* _return */, const std::string& /* key */) {
    return;
  }
  bool remove(const std::string& /* key */) {
    bool _return = false;
    return _return;
  }
};

typedef struct _TVRDailyInjectionsStoreService_add_args__isset {
  _TVRDailyInjectionsStoreService_add_args__isset() : key(false), registrationId(false) {}
  bool key;
  bool registrationId;
} _TVRDailyInjectionsStoreService_add_args__isset;

class TVRDailyInjectionsStoreService_add_args {
 public:

  TVRDailyInjectionsStoreService_add_args() : key(), registrationId(0) {
  }

  virtual ~TVRDailyInjectionsStoreService_add_args() throw() {}

  std::string key;
   ::CRDHN::VR::Data::TRID registrationId;

  _TVRDailyInjectionsStoreService_add_args__isset __isset;

  void __set_key(const std::string& val) {
    key = val;
  }

  void __set_registrationId(const  ::CRDHN::VR::Data::TRID val) {
    registrationId = val;
  }

  bool operator == (const TVRDailyInjectionsStoreService_add_args & rhs) const
  {
    if (!(key == rhs.key))
      return false;
    if (!(registrationId == rhs.registrationId))
      return false;
    return true;
  }
  bool operator != (const TVRDailyInjectionsStoreService_add_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TVRDailyInjectionsStoreService_add_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class TVRDailyInjectionsStoreService_add_pargs {
 public:


  virtual ~TVRDailyInjectionsStoreService_add_pargs() throw() {}

  const std::string* key;
  const  ::CRDHN::VR::Data::TRID* registrationId;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TVRDailyInjectionsStoreService_add_result__isset {
  _TVRDailyInjectionsStoreService_add_result__isset() : success(false) {}
  bool success;
} _TVRDailyInjectionsStoreService_add_result__isset;

class TVRDailyInjectionsStoreService_add_result {
 public:

  TVRDailyInjectionsStoreService_add_result() : success(0) {
  }

  virtual ~TVRDailyInjectionsStoreService_add_result() throw() {}

  bool success;

  _TVRDailyInjectionsStoreService_add_result__isset __isset;

  void __set_success(const bool val) {
    success = val;
  }

  bool operator == (const TVRDailyInjectionsStoreService_add_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const TVRDailyInjectionsStoreService_add_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TVRDailyInjectionsStoreService_add_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TVRDailyInjectionsStoreService_add_presult__isset {
  _TVRDailyInjectionsStoreService_add_presult__isset() : success(false) {}
  bool success;
} _TVRDailyInjectionsStoreService_add_presult__isset;

class TVRDailyInjectionsStoreService_add_presult {
 public:


  virtual ~TVRDailyInjectionsStoreService_add_presult() throw() {}

  bool* success;

  _TVRDailyInjectionsStoreService_add_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _TVRDailyInjectionsStoreService_get_args__isset {
  _TVRDailyInjectionsStoreService_get_args__isset() : key(false) {}
  bool key;
} _TVRDailyInjectionsStoreService_get_args__isset;

class TVRDailyInjectionsStoreService_get_args {
 public:

  TVRDailyInjectionsStoreService_get_args() : key() {
  }

  virtual ~TVRDailyInjectionsStoreService_get_args() throw() {}

  std::string key;

  _TVRDailyInjectionsStoreService_get_args__isset __isset;

  void __set_key(const std::string& val) {
    key = val;
  }

  bool operator == (const TVRDailyInjectionsStoreService_get_args & rhs) const
  {
    if (!(key == rhs.key))
      return false;
    return true;
  }
  bool operator != (const TVRDailyInjectionsStoreService_get_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TVRDailyInjectionsStoreService_get_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class TVRDailyInjectionsStoreService_get_pargs {
 public:


  virtual ~TVRDailyInjectionsStoreService_get_pargs() throw() {}

  const std::string* key;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TVRDailyInjectionsStoreService_get_result__isset {
  _TVRDailyInjectionsStoreService_get_result__isset() : success(false) {}
  bool success;
} _TVRDailyInjectionsStoreService_get_result__isset;

class TVRDailyInjectionsStoreService_get_result {
 public:

  TVRDailyInjectionsStoreService_get_result() {
  }

  virtual ~TVRDailyInjectionsStoreService_get_result() throw() {}

   ::CRDHN::VR::Data::TDailyInjections success;

  _TVRDailyInjectionsStoreService_get_result__isset __isset;

  void __set_success(const  ::CRDHN::VR::Data::TDailyInjections& val) {
    success = val;
  }

  bool operator == (const TVRDailyInjectionsStoreService_get_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const TVRDailyInjectionsStoreService_get_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TVRDailyInjectionsStoreService_get_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TVRDailyInjectionsStoreService_get_presult__isset {
  _TVRDailyInjectionsStoreService_get_presult__isset() : success(false) {}
  bool success;
} _TVRDailyInjectionsStoreService_get_presult__isset;

class TVRDailyInjectionsStoreService_get_presult {
 public:


  virtual ~TVRDailyInjectionsStoreService_get_presult() throw() {}

   ::CRDHN::VR::Data::TDailyInjections* success;

  _TVRDailyInjectionsStoreService_get_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _TVRDailyInjectionsStoreService_remove_args__isset {
  _TVRDailyInjectionsStoreService_remove_args__isset() : key(false) {}
  bool key;
} _TVRDailyInjectionsStoreService_remove_args__isset;

class TVRDailyInjectionsStoreService_remove_args {
 public:

  TVRDailyInjectionsStoreService_remove_args() : key() {
  }

  virtual ~TVRDailyInjectionsStoreService_remove_args() throw() {}

  std::string key;

  _TVRDailyInjectionsStoreService_remove_args__isset __isset;

  void __set_key(const std::string& val) {
    key = val;
  }

  bool operator == (const TVRDailyInjectionsStoreService_remove_args & rhs) const
  {
    if (!(key == rhs.key))
      return false;
    return true;
  }
  bool operator != (const TVRDailyInjectionsStoreService_remove_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TVRDailyInjectionsStoreService_remove_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class TVRDailyInjectionsStoreService_remove_pargs {
 public:


  virtual ~TVRDailyInjectionsStoreService_remove_pargs() throw() {}

  const std::string* key;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TVRDailyInjectionsStoreService_remove_result__isset {
  _TVRDailyInjectionsStoreService_remove_result__isset() : success(false) {}
  bool success;
} _TVRDailyInjectionsStoreService_remove_result__isset;

class TVRDailyInjectionsStoreService_remove_result {
 public:

  TVRDailyInjectionsStoreService_remove_result() : success(0) {
  }

  virtual ~TVRDailyInjectionsStoreService_remove_result() throw() {}

  bool success;

  _TVRDailyInjectionsStoreService_remove_result__isset __isset;

  void __set_success(const bool val) {
    success = val;
  }

  bool operator == (const TVRDailyInjectionsStoreService_remove_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const TVRDailyInjectionsStoreService_remove_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TVRDailyInjectionsStoreService_remove_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TVRDailyInjectionsStoreService_remove_presult__isset {
  _TVRDailyInjectionsStoreService_remove_presult__isset() : success(false) {}
  bool success;
} _TVRDailyInjectionsStoreService_remove_presult__isset;

class TVRDailyInjectionsStoreService_remove_presult {
 public:


  virtual ~TVRDailyInjectionsStoreService_remove_presult() throw() {}

  bool* success;

  _TVRDailyInjectionsStoreService_remove_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class TVRDailyInjectionsStoreServiceClient : virtual public TVRDailyInjectionsStoreServiceIf {
 public:
  TVRDailyInjectionsStoreServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  TVRDailyInjectionsStoreServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  bool add(const std::string& key, const  ::CRDHN::VR::Data::TRID registrationId);
  void send_add(const std::string& key, const  ::CRDHN::VR::Data::TRID registrationId);
  bool recv_add();
  void get( ::CRDHN::VR::Data::TDailyInjections& _return, const std::string& key);
  void send_get(const std::string& key);
  void recv_get( ::CRDHN::VR::Data::TDailyInjections& _return);
  bool remove(const std::string& key);
  void send_remove(const std::string& key);
  bool recv_remove();
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class TVRDailyInjectionsStoreServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<TVRDailyInjectionsStoreServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (TVRDailyInjectionsStoreServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_add(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_get(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_remove(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  TVRDailyInjectionsStoreServiceProcessor(boost::shared_ptr<TVRDailyInjectionsStoreServiceIf> iface) :
    iface_(iface) {
    processMap_["add"] = &TVRDailyInjectionsStoreServiceProcessor::process_add;
    processMap_["get"] = &TVRDailyInjectionsStoreServiceProcessor::process_get;
    processMap_["remove"] = &TVRDailyInjectionsStoreServiceProcessor::process_remove;
  }

  virtual ~TVRDailyInjectionsStoreServiceProcessor() {}
};

class TVRDailyInjectionsStoreServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  TVRDailyInjectionsStoreServiceProcessorFactory(const ::boost::shared_ptr< TVRDailyInjectionsStoreServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< TVRDailyInjectionsStoreServiceIfFactory > handlerFactory_;
};

class TVRDailyInjectionsStoreServiceMultiface : virtual public TVRDailyInjectionsStoreServiceIf {
 public:
  TVRDailyInjectionsStoreServiceMultiface(std::vector<boost::shared_ptr<TVRDailyInjectionsStoreServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~TVRDailyInjectionsStoreServiceMultiface() {}
 protected:
  std::vector<boost::shared_ptr<TVRDailyInjectionsStoreServiceIf> > ifaces_;
  TVRDailyInjectionsStoreServiceMultiface() {}
  void add(boost::shared_ptr<TVRDailyInjectionsStoreServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  bool add(const std::string& key, const  ::CRDHN::VR::Data::TRID registrationId) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->add(key, registrationId);
    }
    return ifaces_[i]->add(key, registrationId);
  }

  void get( ::CRDHN::VR::Data::TDailyInjections& _return, const std::string& key) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->get(_return, key);
    }
    ifaces_[i]->get(_return, key);
    return;
  }

  bool remove(const std::string& key) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->remove(key);
    }
    return ifaces_[i]->remove(key);
  }

};

}} // namespace

#endif
