/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef vreventinfostoreservice_CONSTANTS_H
#define vreventinfostoreservice_CONSTANTS_H

#include "vreventinfostoreservice_types.h"

namespace CRDHN { namespace VR {

class vreventinfostoreserviceConstants {
 public:
  vreventinfostoreserviceConstants();

};

extern const vreventinfostoreserviceConstants g_vreventinfostoreservice_constants;

}} // namespace

#endif
