/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef vrcentremanagerservice_CONSTANTS_H
#define vrcentremanagerservice_CONSTANTS_H

#include "vrcentremanagerservice_types.h"

namespace CRDHN { namespace VR {

class vrcentremanagerserviceConstants {
 public:
  vrcentremanagerserviceConstants();

};

extern const vrcentremanagerserviceConstants g_vrcentremanagerservice_constants;

}} // namespace

#endif
