/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "vrdailyinjectionsstoreservice_constants.h"

namespace CRDHN { namespace VR {

const vrdailyinjectionsstoreserviceConstants g_vrdailyinjectionsstoreservice_constants;

vrdailyinjectionsstoreserviceConstants::vrdailyinjectionsstoreserviceConstants() {
}

}} // namespace

