/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef vrdailyinjectionsstoreservice_CONSTANTS_H
#define vrdailyinjectionsstoreservice_CONSTANTS_H

#include "vrdailyinjectionsstoreservice_types.h"

namespace CRDHN { namespace VR {

class vrdailyinjectionsstoreserviceConstants {
 public:
  vrdailyinjectionsstoreserviceConstants();

};

extern const vrdailyinjectionsstoreserviceConstants g_vrdailyinjectionsstoreservice_constants;

}} // namespace

#endif
