/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "flogservice_constants.h"

namespace CRDHN { namespace Common { namespace Log {

const flogserviceConstants g_flogservice_constants;

flogserviceConstants::flogserviceConstants() {
}

}}} // namespace

