/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "stringtoi32setservice_constants.h"

namespace CRDHN { namespace Common {

const stringtoi32setserviceConstants g_stringtoi32setservice_constants;

stringtoi32setserviceConstants::stringtoi32setserviceConstants() {
}

}} // namespace

