/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "vr_response_constants.h"

namespace CRDHN { namespace VR { namespace Response {

const vr_responseConstants g_vr_response_constants;

vr_responseConstants::vr_responseConstants() {
}

}}} // namespace

