/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package crdhn.vr.thrift.data;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class TDailyInjections implements org.apache.thrift.TBase<TDailyInjections, TDailyInjections._Fields>, java.io.Serializable, Cloneable, Comparable<TDailyInjections> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TDailyInjections");

  private static final org.apache.thrift.protocol.TField REGISTRATIONS_FIELD_DESC = new org.apache.thrift.protocol.TField("registrations", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TDailyInjectionsStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TDailyInjectionsTupleSchemeFactory());
  }

  public List<Long> registrations; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    REGISTRATIONS((short)1, "registrations");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // REGISTRATIONS
          return REGISTRATIONS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.REGISTRATIONS, new org.apache.thrift.meta_data.FieldMetaData("registrations", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64            , "TRID"))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TDailyInjections.class, metaDataMap);
  }

  public TDailyInjections() {
  }

  public TDailyInjections(
    List<Long> registrations)
  {
    this();
    this.registrations = registrations;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TDailyInjections(TDailyInjections other) {
    if (other.isSetRegistrations()) {
      List<Long> __this__registrations = new ArrayList<Long>(other.registrations.size());
      for (Long other_element : other.registrations) {
        __this__registrations.add(other_element);
      }
      this.registrations = __this__registrations;
    }
  }

  public TDailyInjections deepCopy() {
    return new TDailyInjections(this);
  }

  @Override
  public void clear() {
    this.registrations = null;
  }

  public int getRegistrationsSize() {
    return (this.registrations == null) ? 0 : this.registrations.size();
  }

  public java.util.Iterator<Long> getRegistrationsIterator() {
    return (this.registrations == null) ? null : this.registrations.iterator();
  }

  public void addToRegistrations(long elem) {
    if (this.registrations == null) {
      this.registrations = new ArrayList<Long>();
    }
    this.registrations.add(elem);
  }

  public List<Long> getRegistrations() {
    return this.registrations;
  }

  public TDailyInjections setRegistrations(List<Long> registrations) {
    this.registrations = registrations;
    return this;
  }

  public void unsetRegistrations() {
    this.registrations = null;
  }

  /** Returns true if field registrations is set (has been assigned a value) and false otherwise */
  public boolean isSetRegistrations() {
    return this.registrations != null;
  }

  public void setRegistrationsIsSet(boolean value) {
    if (!value) {
      this.registrations = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case REGISTRATIONS:
      if (value == null) {
        unsetRegistrations();
      } else {
        setRegistrations((List<Long>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case REGISTRATIONS:
      return getRegistrations();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case REGISTRATIONS:
      return isSetRegistrations();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TDailyInjections)
      return this.equals((TDailyInjections)that);
    return false;
  }

  public boolean equals(TDailyInjections that) {
    if (that == null)
      return false;

    boolean this_present_registrations = true && this.isSetRegistrations();
    boolean that_present_registrations = true && that.isSetRegistrations();
    if (this_present_registrations || that_present_registrations) {
      if (!(this_present_registrations && that_present_registrations))
        return false;
      if (!this.registrations.equals(that.registrations))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(TDailyInjections other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetRegistrations()).compareTo(other.isSetRegistrations());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRegistrations()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.registrations, other.registrations);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TDailyInjections(");
    boolean first = true;

    sb.append("registrations:");
    if (this.registrations == null) {
      sb.append("null");
    } else {
      sb.append(this.registrations);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TDailyInjectionsStandardSchemeFactory implements SchemeFactory {
    public TDailyInjectionsStandardScheme getScheme() {
      return new TDailyInjectionsStandardScheme();
    }
  }

  private static class TDailyInjectionsStandardScheme extends StandardScheme<TDailyInjections> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TDailyInjections struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // REGISTRATIONS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list104 = iprot.readListBegin();
                struct.registrations = new ArrayList<Long>(_list104.size);
                for (int _i105 = 0; _i105 < _list104.size; ++_i105)
                {
                  long _elem106;
                  _elem106 = iprot.readI64();
                  struct.registrations.add(_elem106);
                }
                iprot.readListEnd();
              }
              struct.setRegistrationsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TDailyInjections struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.registrations != null) {
        oprot.writeFieldBegin(REGISTRATIONS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I64, struct.registrations.size()));
          for (long _iter107 : struct.registrations)
          {
            oprot.writeI64(_iter107);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TDailyInjectionsTupleSchemeFactory implements SchemeFactory {
    public TDailyInjectionsTupleScheme getScheme() {
      return new TDailyInjectionsTupleScheme();
    }
  }

  private static class TDailyInjectionsTupleScheme extends TupleScheme<TDailyInjections> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TDailyInjections struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetRegistrations()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetRegistrations()) {
        {
          oprot.writeI32(struct.registrations.size());
          for (long _iter108 : struct.registrations)
          {
            oprot.writeI64(_iter108);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TDailyInjections struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list109 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I64, iprot.readI32());
          struct.registrations = new ArrayList<Long>(_list109.size);
          for (int _i110 = 0; _i110 < _list109.size; ++_i110)
          {
            long _elem111;
            _elem111 = iprot.readI64();
            struct.registrations.add(_elem111);
          }
        }
        struct.setRegistrationsIsSet(true);
      }
    }
  }

}

